### ISSUE TITLE
commit?

### ISSUE THREAD

**Issue by AndreaPollini** [5AI-2015-TPI-pollini/progetto-java-xml-saraseward#1]
Quando una funzionalità è stata terminata è utile fare un push sul server. la descrizione va abbastanza bene anche se sarebbe interessante avere anche una descrizione della struttura dell'applicazione dal punto di vista tecnico.

**Comment by saraseward** [comment]
Ok per il push sul server.
Come già scritto, la descrizione è temporanea.
La mia intenzione non era quella di scriverla ieri, ma a progetto finito così da poter descrivere il progetto per come è realmente, senza perdere tempo a descrivere dettagli tecnici che poi cambierò.
